version: '3'

tasks:
  build:
    cmds:
      - go build -v -o babel-agent
      - cp babel-agent $GOBIN

  load:
    cmds:
      - launchctl bootstrap /Library/LaunchAgents/org.babel.agent.plist

  list:
    cmds:
      - launchctl list | grep org.babel.agent

  unload:
    cmds:
      - launchctl bootout /Library/LaunchAgents/org.babel.agent.plist