version: '3'

# https://taskfile.dev/usage/

tasks:
  build:
    cmds:
      - go build -v -o babel-agent #- cp babel-agent $GOBIN

  load:
    cmds:
      - |
        USER_ID=$(id -u)
        echo "Using user ID: $USER_ID for launchctl bootstrap"
        launchctl bootstrap gui/$USER_ID /Library/LaunchDaemons/org.babel.agent.plist      

  list:
    cmds:
      - launchctl list | grep org.babel.agent

  unload:
    cmds:
      - launchctl bootout system /Library/LaunchDaemons/org.babel.agent.plist

  restart:
    cmds:
      - task: unload
      - task: load
      - task: list
