[repository]
path = "$LOCAL_REPO_PATH_TO_BABEL_DATA"
message = "$DEFAULT_COMMIT_MESSAGE"

[user]
username = "$GIT_USERNAME"
email = "$GIT_EMAIL"

[ssh]
passphrase = "$SSH_PASSPHRASE"
filePath = "$SSH_PRIVATE_KEY_PATH"


[agent]
tick = "$TICK (e.g. 10s)"